// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxUlVWPv7PK8RLmQTPrBpyuWFQIbJP1JM',
    appId: '1:299511884999:web:08978caccfd2c0a2f362e2',
    messagingSenderId: '299511884999',
    projectId: 'football-apps-c8870',
    authDomain: 'football-apps-c8870.firebaseapp.com',
    storageBucket: 'football-apps-c8870.firebasestorage.app',
    measurementId: 'G-05XQ8PDZ07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOzMFHr7JMJoh3hTlD6AT5_5zo3f3gda4',
    appId: '1:299511884999:android:716ed7def6567f69f362e2',
    messagingSenderId: '299511884999',
    projectId: 'football-apps-c8870',
    storageBucket: 'football-apps-c8870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEKe8nso2K_a2_4nd7q_SOmwwfTTii0pw',
    appId: '1:299511884999:ios:5c7318c28075b349f362e2',
    messagingSenderId: '299511884999',
    projectId: 'football-apps-c8870',
    storageBucket: 'football-apps-c8870.firebasestorage.app',
    iosBundleId: 'com.example.footballApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEKe8nso2K_a2_4nd7q_SOmwwfTTii0pw',
    appId: '1:299511884999:ios:5c7318c28075b349f362e2',
    messagingSenderId: '299511884999',
    projectId: 'football-apps-c8870',
    storageBucket: 'football-apps-c8870.firebasestorage.app',
    iosBundleId: 'com.example.footballApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxUlVWPv7PK8RLmQTPrBpyuWFQIbJP1JM',
    appId: '1:299511884999:web:6f02416eb53bd947f362e2',
    messagingSenderId: '299511884999',
    projectId: 'football-apps-c8870',
    authDomain: 'football-apps-c8870.firebaseapp.com',
    storageBucket: 'football-apps-c8870.firebasestorage.app',
    measurementId: 'G-6CYR5QGY02',
  );
}
